# 집에서도 깃 환경 세팅

In [ ]:
import numpy as np

In [2]:
arr=np.arange(36).reshape((6,6))

In [3]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [4]:
arr2=np.array([[[ 0,  1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10, 11],
                [12, 13, 14, 15, 16, 17],
                [18, 19, 20, 21, 22, 23],
                [24, 25, 26, 27, 28, 29],
                [30, 31, 32, 33, 34, 35]],
                [[ 0,  1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10, 11],
                [12, 13, 14, 15, 16, 17],
                [18, 19, 20, 21, 22, 23],
                [24, 25, 26, 27, 28, 29],
                [30, 31, 32, 33, 34, 35]],
                [[ 0,  1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10, 11],
                [12, 13, 14, 15, 16, 17],
                [18, 19, 20, 21, 22, 23],
                [24, 25, 26, 27, 28, 29],
                [30, 31, 32, 33, 34, 35]],
                [[ 0,  1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10, 11],
                [12, 13, 14, 15, 16, 17],
                [18, 19, 20, 21, 22, 23],
                [24, 25, 26, 27, 28, 29],
                [30, 31, 32, 33, 34, 35]]])

In [5]:
arr2

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [9]:
arr2[-1,1:5,3:5]

array([[ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28]])

## 클래스, 인스턴스 스태틱 메소드의 이해
- 인스턴스: 각 붕어빵에 대한 설정
- 클래스: 붕어빵 가게에 대한 설정(class 자체에 적용)
- 스태틱:붕어빵과 관련없는 독립적인 설정

In [10]:
class BungeoppangShop:
    """
    붕어빵 가게를 나타내는 클래스입니다.
    이 클래스는 붕어빵을 만들고, 가게의 전반적인 운영을 관리합니다.
    """
    
    # -----------------------------------------------------
    # 1. 클래스 변수: 모든 붕어빵 인스턴스가 공유하는 정보
    # -----------------------------------------------------
    total_bungeoppang_made = 0  # 가게에서 총 몇 개의 붕어빵을 만들었는지 기록 (클래스 전체의 데이터)
    todays_special_filling = "팥" # 오늘의 특별 붕어빵 속재료 (클래스 전체의 설정)

    # -----------------------------------------------------
    # 2. 인스턴스 메소드: 개별 붕어빵 인스턴스에 대한 동작
    # -----------------------------------------------------
    def __init__(self, filling):
        """
        새로운 붕어빵 인스턴스를 만들 때 호출됩니다.
        각 붕어빵은 자신만의 'filling' 속성을 가집니다.
        """
        self.filling = filling  # 이 붕어빵의 속재료 (인스턴스 고유의 데이터)
        BungeoppangShop.total_bungeoppang_made += 1 # 붕어빵 만들 때마다 총 개수 증가

    def eat(self):
        """
        이 붕어빵을 먹는 행위를 나타냅니다.
        'self'를 통해 인스턴스 고유의 'filling'에 접근합니다.
        """
        return f"😋 음~ {self.filling} 붕어빵을 맛있게 먹었습니다!"

    def get_my_info(self):
        """
        이 붕어빵 인스턴스의 정보를 반환합니다.
        """
        return f"✨ 저는 {self.filling} 붕어빵입니다."

    # -----------------------------------------------------
    # 3. 클래스 메소드: 붕어빵 가게(클래스) 전체에 대한 동작
    # -----------------------------------------------------
    @classmethod
    def set_special(cls, new_special_filling):
        """
        오늘의 특별 붕어빵 속재료를 설정합니다.
        'cls'를 통해 클래스 변수인 'todays_special_filling'에 접근하고 변경합니다.
        새로운 특별 붕어빵 인스턴스를 반환할 수도 있습니다.
        """
        cls.todays_special_filling = new_special_filling
        print(f"📢 오늘의 특별 붕어빵 속재료가 '{cls.todays_special_filling}'(으)로 변경되었습니다!")
        # 클래스를 통해 새로운 붕어빵 인스턴스를 만들 수 있습니다.
        return cls(cls.todays_special_filling) 

    @classmethod
    def get_shop_total_made(cls):
        """
        가게에서 지금까지 만든 총 붕어빵 개수를 알려줍니다.
        'cls'를 통해 클래스 변수인 'total_bungeoppang_made'에 접근합니다.
        """
        return f"📈 현재까지 저희 가게에서 총 {cls.total_bungeoppang_made}개의 붕어빵을 만들었습니다."

    # -----------------------------------------------------
    # 4. 정적 메소드: 붕어빵이나 가게와 직접적인 관련 없는 유틸리티 기능
    # -----------------------------------------------------
    @staticmethod
    def display_welcome_message(time_of_day):
        """
        시간대에 따라 다른 환영 메시지를 표시합니다.
        붕어빵 인스턴스나 가게의 상태(self, cls)에 의존하지 않습니다.
        """
        if time_of_day.lower() == "morning":
            return "☀️ 좋은 아침입니다! 따끈한 붕어빵으로 하루를 시작하세요!"
        elif time_of_day.lower() == "evening":
            return "🌙 저녁입니다! 출출할 때 갓 구운 붕어빵 어떠세요?"
        else:
            return "👋 붕어빵 가게에 오신 것을 환영합니다!"

    @staticmethod
    def recommend_drink(temperature):
        """
        날씨 온도에 따라 추천 음료를 알려줍니다.
        가게나 붕어빵의 속성과는 무관한 독립적인 조언입니다.
        """
        if temperature > 25:
            return "🥤 더운 날씨에는 시원한 식혜가 최고죠!"
        else:
            return "☕ 쌀쌀한 날씨에는 따뜻한 아메리카노가 붕어빵과 잘 어울려요!"

# -----------------------------------------------------
# 메소드 사용 예시
# -----------------------------------------------------

print("--- 붕어빵 가게 운영 시작! ---")

# 1. 정적 메소드 사용 예시 (가게나 붕어빵과 무관한 유틸리티)
print(BungeoppangShop.display_welcome_message("morning"))
print(BungeoppangShop.recommend_drink(28))
print("-" * 30)

# 2. 클래스 메소드 사용 예시 (가게 전체의 설정 변경 및 정보 확인)
# 오늘의 특별 붕어빵을 김치맛으로 설정하고, 그 붕어빵을 받습니다.
special_bp = BungeoppangShop.set_special("김치") 
# 클래스 메소드를 통해 현재까지 만들어진 붕어빵 개수를 확인합니다.
print(BungeoppangShop.get_shop_total_made()) 
print("-" * 30)

# 3. 인스턴스 메소드 사용 예시 (개별 붕어빵 다루기)
# 일반 팥 붕어빵과 슈크림 붕어빵을 만듭니다.
red_bean_bp = BungeoppangShop("팥")
custard_bp = BungeoppangShop("슈크림")

# 각 붕어빵 인스턴스의 메소드를 호출합니다.
print(red_bean_bp.get_my_info())
print(red_bean_bp.eat())
print(custard_bp.get_my_info())
print(custard_bp.eat())
print("-" * 30)

# 4. 다시 클래스 메소드로 총 붕어빵 개수 확인
# 위에서 3개(김치, 팥, 슈크림)의 붕어빵이 더 만들어졌으므로, 총 개수가 증가합니다.
print(BungeoppangShop.get_shop_total_made())

print("\n--- 붕어빵 가게 운영 종료! ---")

--- 붕어빵 가게 운영 시작! ---
☀️ 좋은 아침입니다! 따끈한 붕어빵으로 하루를 시작하세요!
🥤 더운 날씨에는 시원한 식혜가 최고죠!
------------------------------
📢 오늘의 특별 붕어빵 속재료가 '김치'(으)로 변경되었습니다!
📈 현재까지 저희 가게에서 총 1개의 붕어빵을 만들었습니다.
------------------------------
✨ 저는 팥 붕어빵입니다.
😋 음~ 팥 붕어빵을 맛있게 먹었습니다!
✨ 저는 슈크림 붕어빵입니다.
😋 음~ 슈크림 붕어빵을 맛있게 먹었습니다!
------------------------------
📈 현재까지 저희 가게에서 총 3개의 붕어빵을 만들었습니다.

--- 붕어빵 가게 운영 종료! ---
